# mkdocs.yml

# --- 网站基本信息 ---
site_name: CS for NCU - 南昌大学计算机学习指北
site_url: https://ncuscc.github.io/cs4ncu/
site_author: 南昌大学超算俱乐部
site_description: '一个由南昌大学超算俱乐部 (NCUSCC) 打造并维护，面向新生的计算机科学入门指南。'

# --- 仓库信息 ---
repo_name: NCUSCC/cs4ncu
repo_url: https://github.com/NCUSCC/cs4ncu
edit_uri: 'edit/main/docs/' # 允许用户直接在 GitHub 上编辑页面

# --- 主题配置 ---
theme:
  name: material
  language: zh # 设置语言为中文
  custom_dir: overrides

  # --- 外观与功能 ---
  # 我们在这里配置日夜间模式切换器。
  # 具体的颜色将由 extra.css 文件精确控制。
  palette:
  - scheme: default
    primary: custom  # <-- 激活自定义颜色
    accent: custom   # <-- 激活自定义颜色
    toggle:
      icon: material/brightness-7
      name: 切换到夜间模式

  # 夜间模式：告诉主题使用你在 CSS 中定义的 'slate' 方案
  - scheme: slate
    primary: custom  # <-- 激活自定义颜色
    accent: custom   # <-- 激活自定义颜色
    toggle:
      icon: material/brightness-4
      name: 切换到日间模式

  # 字体配置 (你的设置很好，予以保留)
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

  # Logo 和 Favicon (建议添加)
  # logo: assets/images/logo.svg
  # favicon: assets/images/favicon.png

  # 增强功能
  features:
    - navigation.tabs # 启用顶部标签页导航
    - navigation.sections # 左侧导航自动展开子章节
    - content.code.copy # 为所有代码块添加“复制”按钮
    - content.code.annotate # 允许代码块注释
    - content.code.select
    - search.suggest # 搜索时提供建议
    - navigation.tags 

# --- 插件配置 (强烈建议添加) ---
plugins:
  - search:
      lang: zh # 启用中文搜索支持
  - tags   # 启用标签系统


# --- Markdown 扩展 (增强内容显示) ---
# 合并后的 mkdocs.yml 配置

markdown_extensions:
  # --- 基础与美化扩展 ---

  # Admonition: 漂亮的提示框 (note, warning, tip 等)
  - admonition

  # Details: 可折叠的内容块
  - pymdownx.details
  
  # SmartyPants: 自动将普通标点转换为更美观的印刷体标点
  - pymdownx.smartsymbols

  # Tabbed: 创建可以切换内容的标签页
  - pymdownx.tabbed:
      alternate_style: true

  # --- 代码与高亮扩展 ---

  # SuperFences: 强大的代码块，支持嵌套和图表
  - pymdownx.superfences

  - pymdownx.inlinehilite

  # Highlight: 为代码块提供语法高亮 (合并了两个列表的配置)
  - pymdownx.highlight:
      anchor_linenums: true # 允许链接到代码的特定行
      line_spans: __span    # (来自第二个列表) 方便 CSS 进行更细致的样式控制
      pygments_lang_class: true

  # InlineHilite: 支持行内代码高亮
  - pymdownx.inlinehilite

  # --- 功能与交互扩展 ---

  # Tasklist: 可交互的任务列表/清单
  - pymdownx.tasklist:
      custom_checkbox: true # 允许用 CSS 自定义复选框的样式

  # CriticMarkup: 支持建议修订的语法，方便协作审阅
  - pymdownx.critic

  # TOC (Table of Contents): 自动生成目录
  - toc:
      permalink: true # 为每个标题添加一个永久链接图标

# --- 导航结构 (你的设置很好，予以保留) ---
nav:
  - '首页': 'index.md'
  - '章一：赛博扫盲':
    - '本章导览': 'chapters/ch1-cyber-literacy/index.md'
    - '自助解决问题': 'chapters/ch1-cyber-literacy/01-self-help.md'
    - '认识笔记本电脑': 'chapters/ch1-cyber-literacy/02-laptop.md'
    - '高效打字技巧': 'chapters/ch1-cyber-literacy/03-typing.md'
    - '文件管理基础': 'chapters/ch1-cyber-literacy/04-files.md'
    - '常用软件科普': 'chapters/ch1-cyber-literacy/05-software.md'
    - '开发环境配置': 'chapters/ch1-cyber-literacy/06-development.md'
  - '章二：(规划中)':
    - '敬请期待...': 'chapters/ch2-prelude-to-programming/index.md'
  - '章三：(规划中)':
    - '敬请期待...': 'chapters/ch3-deep-dive/index.md'
  - '章四：(规划中)':
    - '敬请期待...': 'chapters/ch4-data-structures/index.md'
  - '章五：(规划中)':
    - '敬请期待...': 'chapters/ch5-algorithms/index.md'
  - '章六：(规划中)':
    - '敬请期待...': 'chapters/ch6-project-practice/index.md'
  - 指南与社区:
    - 定制化指南:
      - '自定义样式 (CSS)': 'guides/customization/styling.md'
      - '自定义提示框 (Admonition)': 'guides/customization/admonitions.md'
    - 贡献指南:
      - '如何贡献 (How to Contribute)': 'guides/contributing/how-to-contribute.md'
      - '行为准则 (Code of Conduct)': 'guides/contributing/code-of-conduct.md'
      - '写作规范 (Writing Style Guide)': 'guides/contributing/writing-guide.md'
      - '搭建开发环境': 'guides/contributing/development-setup.md'
  - '标签索引': 'tags.md'

# --- 自定义文件链接 (你的设置很好，予以保留) ---
extra_css:
  - 'css/extra.css'
extra_javascript:
  - 'js/custom.js'