site_name: cs4ncu 项目介绍
theme:
  name: material
  palette:
    primary: 'cyan'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Fira Code'
nav:
  - 首页: index.md
  - 第零课：赛博扫盲:
    - 课程介绍: lesson0/intro.md
    - 自助解决问题: lesson0/self-help.md
    - 认识笔记本电脑: lesson0/laptop.md
    - 高效打字技巧: lesson0/typing.md
    - 文件管理基础: lesson0/files.md
    - 常用软件科普: lesson0/software.md
    - 开发环境配置: lesson0/development.md
  - 第一课: lesson1.md
  - 第二课: lesson2.md
  - 第三课: lesson3.md
  - 第四课: lesson4.md
  - 第五课: lesson5.md
  - 第六课: lesson6.md
extra_css:
  - 'css/custom.css'
extra_javascript:
  - 'js/custom.js'